### ISSUE TITLE
Small suggestions

### ISSUE THREAD

**Issue by villeloh** [daniel0707/Home-Cinema#2]
Not sure if already implemented/planned, but you could make it so that you can resize the video by dragging from the corner. Also, there should be a to make the controls/borders visible at all times, even if that's not the default mode. - Ville L.

**Comment by daniel0707** [comment]
Video will be scalable by choosing screen size from settings.
Might implement onLongClick to change placement of AnchorNode.
Controls are available from on screen button.

**Comment by daniel0707** [comment]
Re-positioning video anchor node proved difficult, delaying implementation indefinitely.
Video is now scalable from settings
